# Generated by Django 4.0.2 on 2022-11-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
